name: certificate360
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.6
  dio: ^5.3.2
  common_ui_toolkit:
    git:
      url: https://github.com/ibrahimdeeb0/common_ui_toolkit.git
      ref: main
  get_storage: ^2.0.3
  flutter_smart_dialog: ^4.8.2+3
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  pin_code_fields: ^8.0.1
  curved_navigation_bar:
    git:
      url: https://github.com/hassanannajjar/curved_navigation_bar.git
      ref: master
  flutter_svg: ^1.1.6
  contained_tab_bar_view: ^0.8.0
  url_launcher: ^6.1.7
  google_maps_flutter: ^2.2.3
  # location: ^4.4.0
  flutter_switch: ^0.3.2
  image_picker: ^1.0.4
  intl: ^0.18.0
  webview_flutter: ^4.2.4
  flutter_share: ^2.0.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^15.1.1
  package_info_plus: ^4.1.0
  flutter_rating_bar: ^4.0.1
  flip_card: ^0.7.0
  path_provider: ^2.0.12
  app_settings: ^5.0.0
  connectivity_plus: ^4.0.2
  introduction_screen: ^3.1.1
  flutter_polyline_points: ^2.0.0
  cloud_firestore: ^4.3.1
  flutter_animated_dialog: ^2.0.1
  pdf: ^3.8.4
  open_filex: ^4.3.2
  easy_signature_pad: ^1.0.6
  uuid: ^4.0.0
  flutter_html_to_pdf: ^0.7.0
  dropdown_button2: ^2.3.9
  # flutter_webview_plugin: ^0.4.0
  advance_pdf_viewer: ^2.0.1
  another_flushbar: ^1.12.30
  flutter_barcode_scanner: ^2.0.0
  permission_handler: ^11.0.0
  device_info_plus: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_icons:
  # image_path: "assets/images/launcher_icon.jpg"
  image_path: "assets/images/launcher_debug_icon.jpg"
  ios: true
  android: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/videos/

  fonts:
    - family: Careem
      fonts:
        - asset: assets/fonts/Careem.ttf
